"""Centralized constants for ReelBot pipeline."""

# Timeouts (seconds)
DOWNLOAD_TIMEOUT = 120
AUDIO_EXTRACTION_TIMEOUT = 60
FFPROBE_TIMEOUT = 10
FRAME_EXTRACTION_TIMEOUT = 30
LLM_API_TIMEOUT = 10

# Retry configuration
MAX_RETRIES = 3
RETRY_BASE_DELAY = 1.0
RETRY_MAX_DELAY = 30.0
RETRY_BACKOFF_FACTOR = 2.0

# Pipeline limits
MAX_KEYFRAMES = 8
FRAME_MAX_DIMENSION = 512
